server:
  port: 18080
  
debitedString: An amount of %s has been debited from your account to account:%s. Your available balance is:%s
creditedString: An amount of %s has been credited to your account from account:%s. Your available balance is:%s